### ISSUE TITLE
rexpect seems...slow

### ISSUE THREAD

**Issue by HeavyThumper** [sibson/vncdotool#103]
Processing an rexpect request (png file is 600 bytes, region is 345x20) seems to take about 10 seconds.  Is this "normal"?

This is on version 0.10.0 - if this is corrected in the 0.11.x series then disregard.

**Comment by sibson** [comment]
Hi, 

This appears to be a request for help or support rather than a defect or feature request for vncdotool.  You may have more success getting or finding an answer on [StackOverflow](https://stackoverflow.com/questions/ask?tags=vncdotool).   There are too many variables for me to comment accurately on.  I'd suggest experimenting with different servers to get a better feel for performance.
