### ISSUE TITLE
time-out on expectScreen would come in handy

### ISSUE THREAD

**Issue by jupsoleil** [sibson/vncdotool#109]
Hello all,
I'm using vncdotool in python (from vncdotool import api).
It seems some VNC requests (mousePress) sometimes don't reach my VNC server (maybe due to wifi issues), so expectScreen hangs forever (since the button to reach the to be expected screen was never pushed).  I don't find a way to detect this situation with the present API.

Could a new API call be made for expectScreen with a time-out (and returning true/false/RMS difference - whatever seems best suited)?  Or does someone have another solution tested, like using some pillow calls (https://stackoverflow.com/questions/35176639/compare-images-python-pil)?

Secondly, could a new API call be made, comparing the present screen with a stored image, and returning the RMS difference?  Or should this be done with pillow as well?

Thanks for feedback :).

**Comment by sibson** [comment]
related to #108 108

**Comment by agfor** [comment]
@jupsoleil The API now supports a timeout. I'm also doing some image matching, and I've found using OpenCV works well:

```
import cv2    
import numpy                 

# where screenshot and template are loaded with `cv2.imread("filename.png", 0)`
res = cv2.matchTemplate(screenshot, template, cv2.TM_CCORR_NORMED)
ys, xs = numpy.where(res >= threshold)                            
return list(zip(xs, ys))                                          
```

**Comment by sibson** [comment]
I suspect some of @agfor changes may have addressed the timeout request.

Regarding the API request, I don't think that functionality belongs in the vndo library. Now I think about it I probably should have accepted a function as an argument to the expect() calls rather than an maxrms value.  That would allow users to better customize the difference calculation.  As it stands, I'd accept a PR that factors the rms calculation code out of _expectCompare() and makes it more generally useful and over rideable.
