### ISSUE TITLE
Send command key

### ISSUE THREAD

**Issue by git-gru** [sibson/vncdotool#134]
I want to run the spotlight on mac.
Usually, the short key is command+space.

I used `key cmd-space` but it doesn't work.
Please help me.
Thank you.

**Comment by sibson** [comment]
Hi, 

This appears to be a request for help or support rather than a defect or feature request for vncdotool.  The GitHub project is used for development of vncdotool. You may have more success getting or finding an answer on [StackOverflow](https://stackoverflow.com/questions/ask?tags=vncdotool)

It could be the cmd doesn't map the to apple key in the vnc protocol.
