### ISSUE TITLE
Capture is not working MacOS on 0.12.1

### ISSUE THREAD

**Issue by arossert** [sibson/vncdotool#145]
I'm using vncdotool to control a Linux machine using Vmware Fusion, everything is working as expected except for the capture feature. 
When I submit a capture command I get a file with one pixel in it sized 69b, the command is:

`vncdo -s 127.0.0.1::5900 capture pic.png`

The file generated has one small pixel in it, if the screen is black then it is black and if the screen is blue than it is blue so it seems that the capture is kinda working.

Is there anything that needs to be configured to make it work?

**System information:**
vncdotool version - 0.12.1
Pillow version - 5.4.1
Vmware Fusion - 10.1.5
MacOS - 10.14.3 (Mojave)
Python version -  2.7.15 (tried with 3.6 with the same results)
VNC server - Built in Vmware Fusion

**Update:**
Tested on vncdotool version 0.11.2 and it seems to fix the issue (0.12.0 didn't work as well)

**Update2:**
I have looked at the code and it seems that the issue is with the screen size in this function:
```
def _captureSave(self, data, filename, *args):
  log.debug('captureSave %s', filename)
  if args:
      capture = self.screen.crop(args)
  else:
      capture = self.screen
  capture.save(filename)

  return self
```
When I debug it I see that `self.screen.size` is a tuple of `(1,1)` when it should be `(800,600)` I'm willing to provide a fix but I have no idea where to start.
On version 0.11.2 it works but it does not seem that the changes are related, maybe something with the server version.

**Comment by arossert** [comment]
@sibson can you please address this issue? I need the capture/expect features to work so currently I'm reverting to version 0.11.2 but I want to use the latest version.

**Comment by sibson** [comment]
There is little I can personally do, I don't have VMWare.  It sounds like the server is sending back an incremental update or a pseudo-update vncdo doesn't expect/recognize.  Doing something similar to this [PR](https://github.com/sibson/vncdotool/pull/142) forcing a full update might help.  Otherwise, running with ```--vvv``` and adding some logging to track what updateReactangle calls are being seen is the best way to debug the issue.

**Comment by arossert** [comment]
Thanks for the fast replay, this is the output with `-vvv` on both versions:

V0.12.1(not working):
```
INFO:root:connecting to 127.0.0.1:5901
INFO:twisted:Starting factory <vncdotool.command.VNCDoCLIFactory instance at 0x108fcda28>
INFO:twisted:Using protocol version 3.800
INFO:root:connected to Windows 10 x64
DEBUG:vncdotool.client:captureScreen 0.12.1.png
DEBUG:vncdotool.client:captureSave 0.12.1.png
INFO:twisted:Stopping factory <vncdotool.command.VNCDoCLIFactory instance at 0x108fcda28>
INFO:twisted:Main loop terminated.
```

V0.11.2 (working):
```
INFO:root:connecting to 127.0.0.1:5901
INFO:twisted:Starting factory <vncdotool.command.VNCDoCLIFactory instance at 0x10ad3bb90>
INFO:twisted:Protocol version 3.800 not supported
INFO:twisted:Using protocol version 3.300
INFO:root:connected to Windows 10 x64
DEBUG:vncdotool.client:captureScreen 0.11.2.png
DEBUG:vncdotool.client:captureSave 0.11.2.png
INFO:twisted:Stopping factory <vncdotool.command.VNCDoCLIFactory instance at 0x10ad3bb90>
INFO:twisted:Main loop terminated.
```

The only difference that I can see is the protocol version, it is using 3.300 on v0.11.2 and 3.800 on v0.12.1, is there a way to force the protocol version?

Regarding PR #141, as far as I can see it is only for `expect` and not for `capture`, how can I use it in my case?

**Comment by arossert** [comment]
@sibson I have submitted #149 to add the ability to control this flag in the `captureScreen` function.
May you please review it and give me your input?

**Comment by sibson** [comment]
https://github.com/sibson/vncdotool/pull/125 added support for version 3.8. Perhaps we need to control the version or max version from the command line too?

**Comment by pmhahn** [comment]
> Vmware Fusion - 10.1.5

Some (previous?) versions of VMware had a bug and start sending a _single pixle_ update instead of the full screen. Because of that there is a `VMWareFactory` in [vncdotool/client.py](vncdotool/client.py) to work-around that bug. (Actually the code looks broken). Sadly `vncdo` does not have an option to switch to that alternative factory.

Also as #149 has been merged long ago I consider this issue stale and I'm closing it for now. If you still experience this issue please feel free to re-open or to create a new PR.

You might also want to give the latest development version a try:
```sh
pip install git+https://github.com/sibson/vncdotool.git@main
```

Be warned that it is Python 3.7+ only.
