### ISSUE TITLE
CRITICAL:root:Connection was refused by other side: 111: Connection refused

### ISSUE THREAD

**Issue by r4venlord** [sibson/vncdotool#150]
I have a problem with vncdotool both from python script and from linux CLI:

vncdotool -v -s 127.0.0.1:5902 capture test.png
INFO:root:connecting to 127.0.0.1:11802
INFO:twisted:Starting factory <vncdotool.command.VNCDoCLIFactory object at 0x7fd05916c160>
CRITICAL:root:Connection was refused by other side: 111: Connection refused.
INFO:twisted:Stopping factory <vncdotool.command.VNCDoCLIFactory object at 0x7fd05916c160>
INFO:twisted:Main loop terminated.

-----------

And also from python script:

#!/usr/bin/python3
from vncdotool import api

client = api.connect('127.0.0.1:5902', password="xxx")
client.captureScreen('screenshot.png')
client.disconnect()

./vnctool.py
Traceback (most recent call last):
  File "./vnctool.py", line 6, in <module>
    client.captureScreen('screenshot.png')
  File "/home/user/.local/lib/python3.5/site-packages/vncdotool/api.py", line 108, in proxy_call
    raise VNCDoException(result)
vncdotool.api.VNCDoException: [Failure instance: Traceback (failure with no frames): <class 'twisted.internet.error.ConnectionRefusedError'>: Connection was refused by other side: 111: Connection refused.
]

------------

Have  tried to find someone else with the same issue but haven't found any yet.

I have tried to tcpdump and use vncdotool from another server and when looking into tcpdump i do not recieve any connection on specified port.

It works to telnet from internal & external:

telnet localhost 5902
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
RFB 003.008

 Have you included the following information?

 - Xvnc version TightVNC-1.3.9
 - vncdotool 0.12.1

Hope that someone will find out a solution.

**Comment by alex2304** [comment]
Faced almost the same issue.

I "solved" it in the following way:

1) Connect to the server via VNC Viewer (or may be some other client also can suit, but I used this one)
2) In the connection properties, choose <b>Medium or High quality of image - it's important!</b> Connect with new settings.
3) Close connection of VNC Viewer, and try to connect using VNCDoTool. In my case, after that strange manipulation it works.

I suggest that some variable related to image quality is needed to be sent to the server. 
Started to read RFB specification.

**Comment by Bnaya** [comment]
I'm having the same issue using the CLI
My vnc server is the one on selenium docker
https://github.com/SeleniumHQ/docker-selenium

**Comment by stobias123** [comment]
I have this issue, pulling my hair out trying to figure out what's going on.

**Comment by stobias123** [comment]
update - this was solved by setting no password. related to #172 I think.

**Comment by samiraguiar** [comment]
I just had this problem and in the end I was misunderstanding the documentation. There are three ways to specify the server to connect to:
- With the VNC display:
`vncdo -s 192.168.100.1:3` (connect to VNC display `:3`)
- With the port where the VNC server is running:
`vncdo -s 192.168.100.1::5903` (note the two colons between the IP and the port)
- Without any of the above:
`vncdo -s 192.168.100.1` (will use the default port `5900`)

From the log excerpt posted by @r4venlord:
> vncdotool -v -s 127.0.0.1:5902 capture test.png
> INFO:root:connecting to 127.0.0.1:**11802**

Note the strange port that vncdotool is trying to connect to. That's because the server was specified using a single colon instead of two, and vncdotool uses what comes after the colon as the display, not the port. The resulting port "11802" is equal to `5902 + 5900`, as this is how it guesses the port from the display when [parsing the server](https://github.com/sibson/vncdotool/blob/d7a98e2925ac2885ffdd6996cbd0491e3e2d6759/vncdotool/command.py#L300) parameter.

@sibson maybe this could be clarified in the docs? I can open a PR if you like.

**Comment by sibson** [comment]
Hi, @samiraguiar thanks help out here. A PR to update to the docs would be great.

**Comment by pmhahn** [comment]
This is already documented in `README.rsr` line 26-33 since 0df0f135

**Comment by sibson** [comment]
I was hoping a PR would explain it better but as one doesn't seem to be forthcoming, I'll close this issue.
